pipeline {
	agent{
		docker{
			image 'maven:3.6.1-jdk-8-slim'
			args '-v $HOME/.m2:/root/.m2'
		}
	}
	
	stages{
		stage("build"){
			steps{
				echo 'Compiling worker app'
				dir('worker'){
				sh 'mvn compile'
				}
			}
		}
		stage("test"){
			steps{
				echo 'Running Unit Tets on worker app'
				dir('worker'){
					sh 'mvn clean test'
				}
			}
		}
		stage("package"){
			steps{
				echo 'Packaging worker app 2022-12-10'
				dir('worker'){
					sh 'mvn package -DskipTests'
					archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
				}
			}
		}
		stage('docker-package'){
			agent any
			steps{
				echo 'Packaging worker app with docker'
				script{
					docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
						def workerImage = docker.build("aminsh86/worker:v${env.BUILD_ID}", "./worker")
						workerImage.push()
						workerImage.push("latest")
					}
				}
			}
		}
	}
	post{
		always{
			echo 'Job is completed.. 2022-12-10 17:58'
		}
	}
}
